### ISSUE TITLE
?

### ISSUE THREAD

**Issue by otgo** [Pitasi/TagAlertBot#2]
what's this pitasi?
`
root@vps273405:~/TgBash/TagAlertBot# ./main.py
Traceback (most recent call last):
  File "./main.py", line 15, in <module>
    from config import *
ImportError: No module named 'config'
`

**Comment by pitasi** [comment]
Hi.
The repository was missing the configuration file.

By the way, today I made some major changes (rewritten all from 0) so you may want to check it out.
Running the bot by yourself is much much simpler.

I'm closing here ;)
